name: my first workflow
on: push
jobs:
    firstjob:
        runs-on: ubuntu-latest
        steps:
        -   name: list
            run: uname
        -   name: read
            run: cat ReadMe.md

    secondjob:
        runs-on: ubuntu
        steps:
        -   name: Install
            run: yum install telnet        
        